// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCduyKf-owTvw_q-E5gxQg4GnUs7plNKvI',
    appId: '1:594499379076:web:3d2b0af933c5e4ce9747d1',
    messagingSenderId: '594499379076',
    projectId: 'app1-33860',
    authDomain: 'app1-33860.firebaseapp.com',
    storageBucket: 'app1-33860.firebasestorage.app',
    measurementId: 'G-6XKB6TVPP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCywfcXgtctQ-lHjNGLs5YZsJU5FTOLSyk',
    appId: '1:594499379076:android:7428d318ab846e749747d1',
    messagingSenderId: '594499379076',
    projectId: 'app1-33860',
    storageBucket: 'app1-33860.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuoyvuZOWGQK4sWh4vAXIj6TdagjKTnoE',
    appId: '1:594499379076:ios:c3008555405e3a039747d1',
    messagingSenderId: '594499379076',
    projectId: 'app1-33860',
    storageBucket: 'app1-33860.firebasestorage.app',
    iosBundleId: 'com.hanajun.myapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuoyvuZOWGQK4sWh4vAXIj6TdagjKTnoE',
    appId: '1:594499379076:ios:19def42852b7fdd69747d1',
    messagingSenderId: '594499379076',
    projectId: 'app1-33860',
    storageBucket: 'app1-33860.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCduyKf-owTvw_q-E5gxQg4GnUs7plNKvI',
    appId: '1:594499379076:web:85904963460879909747d1',
    messagingSenderId: '594499379076',
    projectId: 'app1-33860',
    authDomain: 'app1-33860.firebaseapp.com',
    storageBucket: 'app1-33860.firebasestorage.app',
    measurementId: 'G-4VDJXQZ3W2',
  );
}
